import mongoose from "mongoose";
import { Product } from "./model/Product";
import dotenv from "dotenv";

dotenv.config();

const products = [
  {
    title: "Nike Air Zoom Runner",
    description:
      "Lightweight running sneakers designed for everyday training and comfort.",
    category: "shoes",
    subCategory: "sneakers",
    brand: "nike",
    gender: "men",
    sizes: ["41", "42", "43", "44"],
    price: 120,
    rating: 4,
    stock: 15,
    images: [],
  },
  {
    title: "Adidas Ultraboost Light",
    description:
      "Premium running sneakers with responsive cushioning and breathable mesh.",
    category: "shoes",
    subCategory: "sneakers",
    brand: "adidas",
    gender: "men",
    sizes: ["40", "41", "42", "43"],
    price: 140,
    rating: 5,
    stock: 12,
    images: [],
  },
  {
    title: "New Balance 574 Classic",
    description:
      "Classic everyday sneakers combining comfort, durability and retro style.",
    category: "shoes",
    subCategory: "sneakers",
    brand: "new-balance",
    gender: "unisex",
    sizes: ["39", "40", "41", "42"],
    price: 110,
    rating: 4,
    stock: 18,
    images: [],
  },
  {
    title: "Nike Street Hoodie",
    description: "Soft cotton hoodie perfect for casual everyday wear.",
    category: "clothing",
    subCategory: "jackets",
    brand: "nike",
    gender: "men",
    sizes: ["S", "M", "L", "XL"],
    price: 70,
    rating: 4,
    stock: 20,
    images: [],
  },
  {
    title: "Adidas Sport Jacket",
    description: "Lightweight training jacket designed for outdoor workouts.",
    category: "clothing",
    subCategory: "jackets",
    brand: "adidas",
    gender: "women",
    sizes: ["XS", "S", "M", "L"],
    price: 95,
    rating: 4,
    stock: 14,
    images: [],
  },
  {
    title: "Nike Essential T-Shirt",
    description: "Comfortable cotton t-shirt with classic athletic design.",
    category: "clothing",
    subCategory: "t-shirts",
    brand: "nike",
    gender: "men",
    sizes: ["S", "M", "L"],
    price: 35,
    rating: 4,
    stock: 30,
    images: [],
  },
  {
    title: "Adidas Performance T-Shirt",
    description:
      "Breathable sports t-shirt ideal for gym and training sessions.",
    category: "clothing",
    subCategory: "t-shirts",
    brand: "adidas",
    gender: "men",
    sizes: ["S", "M", "L", "XL"],
    price: 38,
    rating: 4,
    stock: 22,
    images: [],
  },
  {
    title: "New Balance Athletic Tee",
    description: "Minimalist athletic t-shirt with lightweight fabric.",
    category: "clothing",
    subCategory: "t-shirts",
    brand: "new-balance",
    gender: "unisex",
    sizes: ["S", "M", "L"],
    price: 32,
    rating: 4,
    stock: 17,
    images: [],
  },
  {
    title: "Nike Air Max Pulse",
    description: "Modern lifestyle sneakers with comfortable cushioning.",
    category: "shoes",
    subCategory: "sneakers",
    brand: "nike",
    gender: "women",
    sizes: ["37", "38", "39", "40"],
    price: 130,
    rating: 5,
    stock: 10,
    images: [],
  },
  {
    title: "Adidas Cloudfoam Runner",
    description: "Comfortable everyday sneakers with lightweight foam sole.",
    category: "shoes",
    subCategory: "sneakers",
    brand: "adidas",
    gender: "women",
    sizes: ["36", "37", "38", "39"],
    price: 90,
    rating: 4,
    stock: 16,
    images: [],
  },
  {
    title: "New Balance Fresh Foam",
    description: "Running sneakers with soft cushioning for long runs.",
    category: "shoes",
    subCategory: "sneakers",
    brand: "new-balance",
    gender: "men",
    sizes: ["41", "42", "43"],
    price: 125,
    rating: 4,
    stock: 13,
    images: [],
  },
  {
    title: "Nike Training Jacket",
    description: "Warm sports jacket designed for outdoor training.",
    category: "clothing",
    subCategory: "jackets",
    brand: "nike",
    gender: "unisex",
    sizes: ["M", "L", "XL"],
    price: 105,
    rating: 4,
    stock: 11,
    images: [],
  },
  {
    title: "Adidas Casual Jacket",
    description: "Stylish casual jacket with modern athletic design.",
    category: "clothing",
    subCategory: "jackets",
    brand: "adidas",
    gender: "men",
    sizes: ["S", "M", "L"],
    price: 98,
    rating: 4,
    stock: 9,
    images: [],
  },
  {
    title: "New Balance Windbreaker",
    description: "Lightweight windbreaker jacket for cool weather.",
    category: "clothing",
    subCategory: "jackets",
    brand: "new-balance",
    gender: "women",
    sizes: ["XS", "S", "M"],
    price: 88,
    rating: 4,
    stock: 14,
    images: [],
  },
  {
    title: "Nike Urban Tee",
    description: "Casual street style t-shirt with minimalist logo.",
    category: "clothing",
    subCategory: "t-shirts",
    brand: "nike",
    gender: "unisex",
    sizes: ["S", "M", "L", "XL"],
    price: 34,
    rating: 4,
    stock: 25,
    images: [],
  },
  {
    title: "Adidas Everyday Tee",
    description: "Soft everyday t-shirt suitable for casual outfits.",
    category: "clothing",
    subCategory: "t-shirts",
    brand: "adidas",
    gender: "women",
    sizes: ["XS", "S", "M", "L"],
    price: 33,
    rating: 4,
    stock: 19,
    images: [],
  },
  {
    title: "New Balance Training Tee",
    description: "Sport t-shirt made for active workouts.",
    category: "clothing",
    subCategory: "t-shirts",
    brand: "new-balance",
    gender: "men",
    sizes: ["M", "L", "XL"],
    price: 36,
    rating: 4,
    stock: 15,
    images: [],
  },
  {
    title: "Nike Revolution 7",
    description: "Affordable running sneakers with flexible sole.",
    category: "shoes",
    subCategory: "sneakers",
    brand: "nike",
    gender: "men",
    sizes: ["40", "41", "42", "43"],
    price: 85,
    rating: 4,
    stock: 21,
    images: [],
  },
  {
    title: "Adidas Galaxy Trainer",
    description: "Versatile sneakers suitable for running and gym.",
    category: "shoes",
    subCategory: "sneakers",
    brand: "adidas",
    gender: "unisex",
    sizes: ["38", "39", "40", "41"],
    price: 95,
    rating: 4,
    stock: 17,
    images: [],
  },
  {
    title: "New Balance 327 Retro",
    description: "Retro style sneakers with modern comfort.",
    category: "shoes",
    subCategory: "sneakers",
    brand: "new-balance",
    gender: "unisex",
    sizes: ["39", "40", "41", "42"],
    price: 115,
    rating: 5,
    stock: 13,
    images: [],
  },
  {
    title: "Nike Sports Jacket",
    description: "Durable sports jacket with zip closure.",
    category: "clothing",
    subCategory: "jackets",
    brand: "nike",
    gender: "women",
    sizes: ["S", "M", "L"],
    price: 102,
    rating: 4,
    stock: 12,
    images: [],
  },
  {
    title: "Adidas Training Jacket",
    description: "Comfortable training jacket made for active movement.",
    category: "clothing",
    subCategory: "jackets",
    brand: "adidas",
    gender: "unisex",
    sizes: ["M", "L", "XL"],
    price: 100,
    rating: 4,
    stock: 16,
    images: [],
  },
  {
    title: "New Balance Lightweight Jacket",
    description: "Light athletic jacket perfect for cool mornings.",
    category: "clothing",
    subCategory: "jackets",
    brand: "new-balance",
    gender: "men",
    sizes: ["S", "M", "L"],
    price: 92,
    rating: 4,
    stock: 10,
    images: [],
  },
  {
    title: "Nike Classic Tee",
    description: "Classic logo t-shirt for everyday wear.",
    category: "clothing",
    subCategory: "t-shirts",
    brand: "nike",
    gender: "men",
    sizes: ["S", "M", "L", "XL"],
    price: 30,
    rating: 4,
    stock: 27,
    images: [],
  },
  {
    title: "Adidas Logo Tee",
    description: "Simple t-shirt with iconic brand logo.",
    category: "clothing",
    subCategory: "t-shirts",
    brand: "adidas",
    gender: "unisex",
    sizes: ["S", "M", "L"],
    price: 29,
    rating: 4,
    stock: 23,
    images: [],
  },
  {
    title: "New Balance Active Tee",
    description: "Lightweight activewear t-shirt for sports.",
    category: "clothing",
    subCategory: "t-shirts",
    brand: "new-balance",
    gender: "women",
    sizes: ["XS", "S", "M"],
    price: 31,
    rating: 4,
    stock: 18,
    images: [],
  },
  {
    title: "Nike Flex Runner",
    description: "Flexible lightweight sneakers for daily use.",
    category: "shoes",
    subCategory: "sneakers",
    brand: "nike",
    gender: "women",
    sizes: ["36", "37", "38", "39"],
    price: 100,
    rating: 4,
    stock: 14,
    images: [],
  },
  {
    title: "Adidas Swift Run",
    description: "Stylish running sneakers with breathable upper.",
    category: "shoes",
    subCategory: "sneakers",
    brand: "adidas",
    gender: "men",
    sizes: ["41", "42", "43"],
    price: 108,
    rating: 4,
    stock: 11,
    images: [],
  },
  {
    title: "New Balance Running Elite",
    description: "Performance running sneakers with premium cushioning.",
    category: "shoes",
    subCategory: "sneakers",
    brand: "new-balance",
    gender: "men",
    sizes: ["40", "41", "42", "43"],
    price: 135,
    rating: 5,
    stock: 9,
    images: [],
  },
  {
    title: "Nike Sport Hoodie",
    description: "Warm sports hoodie designed for comfort.",
    category: "clothing",
    subCategory: "jackets",
    brand: "nike",
    gender: "unisex",
    sizes: ["M", "L", "XL"],
    price: 85,
    rating: 4,
    stock: 13,
    images: [],
  },
];

const populate = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URL!);
    await Product.deleteMany({});
    await Product.create(products);
    console.log("products was added successfully");
    process.exit(0);
  } catch (ex) {
    console.error(ex);
    process.exit(1);
  }
};

populate();
